### ISSUE TITLE
Data Does not Display Properly (because of 0?)

### ISSUE THREAD

**Issue by lthiery** [apitronics/Hive#11]
![1](https://cloud.githubusercontent.com/assets/1606640/2984238/f4366ef2-dc2f-11e3-8400-de32311e3b2b.png)

Notice that the last reading is of "..." and that the Timestamp is just my time.

![2](https://cloud.githubusercontent.com/assets/1606640/2984239/f61ec30e-dc2f-11e3-896a-cd05aeacbcee.png)

Notice that the datapoint from 8AM exists - but it reads 0. Is that the issue?

**Comment by Detect** [comment]
@lthiery i'm seeing null for the data value. Can you investigate why?
http://cl.ly/image/1u313A22183z

**Comment by Detect** [comment]
looking into honeycomb...
