### ISSUE TITLE
egg/new needs to not create duplicates

### ISSUE THREAD

**Issue by lthiery** [apitronics/Hive#15]
A bee might identify itself multiple times if it ever gets power cycled, effectively hitting port 125 at egg/new with:
`{"sensors": ["0x02", "0x02", "0x02", "0x02", "0x02", "0x02", "0x02", "0x02"],"address":"A"}`

If there exists a Bee with the same address and the same sensors, that Bee and corresponding sensor databases should not be recreated.

What happens when a bee with an existing address has different sensors? A way of "retiring" the previous sensors without deleting their existence would be necessary, so that incoming honey packets can be treated properly but so that historical data is not lost.

**Comment by itdaniher** [comment]
Another refinement might be to eschew with the sensor creation / `hive:125/egg/new` step completely, folding all reports with the same UID & sensor structure into the same bee. New sensor structure would produce a new logical bee.

**Comment by Detect** [comment]
avoids dupe bees/sensor in 40beeff

TODO: better handling when sensors are changed.
