### ISSUE TITLE
Bee address should not be editable

### ISSUE THREAD

**Issue by lthiery** [apitronics/Hive#16]
Firefox only

**Comment by Detect** [comment]
should be disabled from [code](https://github.com/apitronics/Hive/blob/master/Beekeeper/attachments/app/Views/BeeForm.js#L17)

![screen shot 2014-05-27 at 9 46 48 pm](https://cloud.githubusercontent.com/assets/14955/3099953/025ae33a-e60a-11e3-8904-3f3299053772.png)

can you check for JS errors?
