### ISSUE TITLE
optimize loading of sensors and data on bee page

### ISSUE THREAD

**Issue by Detect** [apitronics/Hive#18]

**Comment by rjcorwin** [comment]
Hi @Detect - Just saw this and remembered all the pages that have a noticeable delay before they finish loading. Wanted to mention something I've been thinking about in general with Backbone apps. In the old server-side rendering days users knew that a page was loading by the feedback from their browser telling them that the page was loading. Now that AJAX calls are doing all the heavy lifting the browser ignores those requests and does not indicate anything is happening.  So it's up to us to give that basic feedback to the user that something is loading.  One way to approach this might be a process management system on global App variable that allows code to spawn/kill processes while a View watches processes running and gives visual feedback when there is a process running.  Imagine a route starting with something like...

```
var pid = App.process.spawn()
```

That would return a `Process ID` that would be stored internally. For the View monitoring processes and giving feedback when there are processes present, that code might retrieve active processes doing something like `App.process.list()`.

When that Route is finished doing all of the necessary things it might do something like...

```
App.process.kill(pid)
```

**Comment by Detect** [comment]
@rjsteinert good idea. for "faster" UX, i've spiked a quick solution that renders the bee sensors table as soon as BeeSensors is returned. sensor names are given (copied from sensor defs) on their creation from eggs, so names will show up quicker. table will re-render again with more data when sensor defs and last readings are fetched. i'll revisit again w/ better sol'n as time permits.

**Comment by Detect** [comment]
e512119e916623313dacb6da48b6b90496f43ad8
