### ISSUE TITLE
./utils/install-test-bee needs update for automation branch?

### ISSUE THREAD

**Issue by rjcorwin** [apitronics/Hive#27]
Hi guys - I'm checking out the new functionality behind Device and DeviceDefinition and after running through the new install process that inserts Device Definitions and then running `./util/install-test-bee` and `./util/install-test-data` I get the feeling they might need updating to work correctly.

**Comment by Detect** [comment]
thanks @rjsteinert i'll take a pass at updating the install scripts

**Comment by Detect** [comment]
Fixed in https://github.com/apitronics/Hive/pull/28
